import type {
  AttachmentRecord,
  ChannelRecord,
  ChatMessage,
  DMThread,
  PlatformSettings,
  Profile,
  ServerMembership,
  ServerRecord,
} from "@/lib/types";

const anchor = Date.UTC(2026, 4, 29, 12, 0, 0);
const minutesAgo = (value: number) =>
  new Date(anchor - value * 60_000).toISOString();

export function buildDemoData() {
  const me: Profile = {
    id: "demo-user-1",
    uid: "AETHER-17A9F3",
    username: "Nova",
    displayName: "Nova",
    globalRole: "member",
    title: "spark runner",
    titleColor: "#8bdcff",
    createdAt: minutesAgo(1600),
  };

  const raga: Profile = {
    id: "demo-user-2",
    uid: "AETHER-RG9A01",
    username: "Raga",
    displayName: "Raga",
    globalRole: "primal_lead",
    title: "Team Primals",
    titleColor: "#ffd0df",
    createdAt: minutesAgo(4000),
  };

  const kaysss: Profile = {
    id: "demo-user-3",
    uid: "AETHER-KS4210",
    username: "kaysss",
    displayName: "kaysss",
    globalRole: "primal",
    title: "Team Primals",
    titleColor: "#ffd0df",
    createdAt: minutesAgo(3800),
  };

  const luna: Profile = {
    id: "demo-user-4",
    uid: "AETHER-LN00E2",
    username: "Luna",
    displayName: "Luna",
    globalRole: "member",
    title: "moon florist",
    titleColor: "#ffc7da",
    createdAt: minutesAgo(1220),
  };

  const server1: ServerRecord = {
    id: "server-aurora",
    name: "Aurora Bay",
    description: "A private friends server with soft neon nights and shared plans.",
    inviteCode: "B8F4Q2T9VX",
    ownerId: me.id,
    imageUrl: null,
    theme: "night",
    createdAt: minutesAgo(3200),
    memberCount: 4,
    channelCount: 4,
  };

  const server2: ServerRecord = {
    id: "server-petal",
    name: "Petal Arcade",
    description: "A playful garden of clips, memes, and late-night messages.",
    inviteCode: "H3K2N8P1ZA",
    ownerId: raga.id,
    imageUrl: null,
    theme: "cherry",
    createdAt: minutesAgo(8600),
    memberCount: 3,
    channelCount: 3,
  };

  const server3: ServerRecord = {
    id: "server-ember",
    name: "Ember Hall",
    description: "A warmer room for movie nights, reactions, and quick check-ins.",
    inviteCode: "M5V9R4C0LT",
    ownerId: kaysss.id,
    imageUrl: null,
    theme: "halloween",
    createdAt: minutesAgo(9600),
    memberCount: 3,
    channelCount: 3,
  };

  const channels: ChannelRecord[] = [
    {
      id: "channel-1",
      serverId: server1.id,
      name: "lobby",
      slug: "lobby",
      description: "General conversation and quick pings.",
      position: 0,
      createdAt: minutesAgo(3000),
    },
    {
      id: "channel-2",
      serverId: server1.id,
      name: "media",
      slug: "media",
      description: "Pics, clips, and reaction-worthy chaos.",
      position: 1,
      createdAt: minutesAgo(2500),
    },
    {
      id: "channel-3",
      serverId: server1.id,
      name: "plans",
      slug: "plans",
      description: "Ideas, reminders, and weekend coordination.",
      position: 2,
      createdAt: minutesAgo(1800),
    },
    {
      id: "channel-4",
      serverId: server1.id,
      name: "voice-notes",
      slug: "voice-notes",
      description: "Short clips and casual updates.",
      position: 3,
      createdAt: minutesAgo(1300),
    },
    {
      id: "channel-5",
      serverId: server2.id,
      name: "petals",
      slug: "petals",
      description: "Soft glow check-ins and cute posts.",
      position: 0,
      createdAt: minutesAgo(8400),
    },
    {
      id: "channel-6",
      serverId: server2.id,
      name: "memes",
      slug: "memes",
      description: "Fast laughs and GIF drops.",
      position: 1,
      createdAt: minutesAgo(8300),
    },
    {
      id: "channel-7",
      serverId: server2.id,
      name: "petal-radio",
      slug: "petal-radio",
      description: "Music shares and late-night playlists.",
      position: 2,
      createdAt: minutesAgo(8100),
    },
    {
      id: "channel-8",
      serverId: server3.id,
      name: "ember-chat",
      slug: "ember-chat",
      description: "Warm talk by the fire.",
      position: 0,
      createdAt: minutesAgo(9500),
    },
    {
      id: "channel-9",
      serverId: server3.id,
      name: "screens",
      slug: "screens",
      description: "Show the clip before the room gets loud.",
      position: 1,
      createdAt: minutesAgo(9300),
    },
    {
      id: "channel-10",
      serverId: server3.id,
      name: "after-hours",
      slug: "after-hours",
      description: "The late-night channel with the best replies.",
      position: 2,
      createdAt: minutesAgo(9000),
    },
  ];

  const memberships: ServerMembership[] = [
    {
      serverId: server1.id,
      userId: me.id,
      role: "owner",
      title: "founding spark",
      titleColor: "#a6ffea",
      createdAt: minutesAgo(3200),
    },
    {
      serverId: server1.id,
      userId: raga.id,
      role: "admin",
      title: "team primals",
      titleColor: "#ffd0df",
      createdAt: minutesAgo(2900),
    },
    {
      serverId: server1.id,
      userId: kaysss.id,
      role: "admin",
      title: "team primals",
      titleColor: "#ffd0df",
      createdAt: minutesAgo(2900),
    },
    {
      serverId: server1.id,
      userId: luna.id,
      role: "member",
      title: "night gardener",
      titleColor: "#8bdcff",
      createdAt: minutesAgo(2900),
    },
    {
      serverId: server2.id,
      userId: raga.id,
      role: "owner",
      title: "rose captain",
      titleColor: "#ffc7da",
      createdAt: minutesAgo(8600),
    },
    {
      serverId: server2.id,
      userId: kaysss.id,
      role: "admin",
      title: "petal steward",
      titleColor: "#f6b4ff",
      createdAt: minutesAgo(8400),
    },
    {
      serverId: server2.id,
      userId: luna.id,
      role: "member",
      title: "soft bloom",
      titleColor: "#ffd9e6",
      createdAt: minutesAgo(8100),
    },
    {
      serverId: server3.id,
      userId: kaysss.id,
      role: "owner",
      title: "ember keeper",
      titleColor: "#ffe28f",
      createdAt: minutesAgo(9600),
    },
    {
      serverId: server3.id,
      userId: raga.id,
      role: "admin",
      title: "fire marshal",
      titleColor: "#ffb14e",
      createdAt: minutesAgo(9400),
    },
    {
      serverId: server3.id,
      userId: luna.id,
      role: "member",
      title: "lantern whisperer",
      titleColor: "#ffd878",
      createdAt: minutesAgo(9200),
    },
  ];

  const attachment: AttachmentRecord = {
    url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&q=80",
    name: "night-drive.jpg",
    type: "image",
    mimeType: "image/jpeg",
  };

  const dms: DMThread[] = [
    {
      id: "dm-1",
      memberIds: [me.id, luna.id],
      name: "Luna",
      createdAt: minutesAgo(1680),
      lastMessageAt: minutesAgo(34),
    },
    {
      id: "dm-2",
      memberIds: [me.id, raga.id],
      name: "Raga",
      createdAt: minutesAgo(1420),
      lastMessageAt: minutesAgo(12),
    },
  ];

  const messages: ChatMessage[] = [
    {
      id: "msg-aurora-1",
      serverId: server1.id,
      channelId: channels[0].id,
      authorId: raga.id,
      authorName: raga.displayName,
      authorTitle: "Team Primals",
      authorRole: "primal_lead",
      content: "Server is live. Drop a @Nova ping if you want a channel renamed.",
      kind: "text",
      createdAt: minutesAgo(80),
      mentions: ["Nova"],
    },
    {
      id: "msg-aurora-2",
      serverId: server1.id,
      channelId: channels[0].id,
      authorId: me.id,
      authorName: me.displayName,
      authorTitle: me.title,
      authorRole: "member",
      content: "Making the new space feel calmer tonight. I'll move the media thread after this.",
      kind: "text",
      createdAt: minutesAgo(74),
      replyToId: null,
    },
    {
      id: "msg-aurora-3",
      serverId: server1.id,
      channelId: channels[1].id,
      authorId: luna.id,
      authorName: luna.displayName,
      authorTitle: luna.title,
      authorRole: "member",
      content: "Dropped a sunset clip for the gallery.",
      kind: "image",
      attachment,
      createdAt: minutesAgo(42),
    },
    {
      id: "msg-aurora-4",
      serverId: server1.id,
      channelId: channels[1].id,
      authorId: kaysss.id,
      authorName: kaysss.displayName,
      authorTitle: "Team Primals",
      authorRole: "primal",
      content: "Aether says this room is ready for uploads, replies, and command testing.",
      kind: "text",
      createdAt: minutesAgo(22),
    },
    {
      id: "msg-petal-1",
      serverId: server2.id,
      channelId: channels[5].id,
      authorId: raga.id,
      authorName: raga.displayName,
      authorTitle: "Team Primals",
      authorRole: "primal_lead",
      content: "Cherry blossom theme is gorgeous in here.",
      kind: "text",
      createdAt: minutesAgo(120),
    },
    {
      id: "msg-ember-1",
      serverId: server3.id,
      channelId: channels[7].id,
      authorId: kaysss.id,
      authorName: kaysss.displayName,
      authorTitle: "Team Primals",
      authorRole: "primal",
      content: "Halloween is perfect for this channel. The glow lands just right.",
      kind: "text",
      createdAt: minutesAgo(96),
    },
    {
      id: "msg-dm-1",
      threadId: dms[0].id,
      authorId: luna.id,
      authorName: luna.displayName,
      authorTitle: luna.title,
      authorRole: "member",
      content: "Personal Messages is the cutest rename we could have picked.",
      kind: "text",
      createdAt: minutesAgo(60),
    },
    {
      id: "msg-dm-2",
      threadId: dms[0].id,
      authorId: me.id,
      authorName: me.displayName,
      authorTitle: me.title,
      authorRole: "member",
      content: "It keeps the whole thing feeling more private and less noisy.",
      kind: "text",
      createdAt: minutesAgo(55),
      replyToId: null,
    },
    {
      id: "msg-dm-3",
      threadId: dms[1].id,
      authorId: raga.id,
      authorName: raga.displayName,
      authorTitle: "Team Primals",
      authorRole: "primal_lead",
      content: "If the platform theme feels off, I can switch it for everyone.",
      kind: "system",
      createdAt: minutesAgo(18),
      systemTag: "Aether",
    },
  ];

  const platformSettings: PlatformSettings = {
    theme: "night",
    lastChangedAt: minutesAgo(10),
    lastChangedBy: raga.id,
  };

  return {
    currentUser: me,
    profiles: [me, raga, kaysss, luna],
    servers: [server1, server2, server3],
    channels,
    memberships,
    messages,
    dms,
    platformSettings,
  };
}
